### ISSUE TITLE
add the following animations

### ISSUE THREAD

**Issue by bassochette** [Webeleon/Next-JS-starter-project#178]
```scss
@keyframes fadeIn {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

@keyframes fadeOut {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}

@keyframes pulse {
  0% {
    transform: scale(0.97);
    opacity: 0.5;
  }
  50% {
    transform: scale(1);
    opacity: 0.7;
  }
  100% {
    transform: scale(0.97);
    opacity: 0.5;
  }
}

```
